/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2016-01-18 15:07:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class button_002dtest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<html xmlns:h=\"http://java.sun.com/jsf/html\">\n");
      out.write("<head>\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/bootstrap.min.css\">\n");
      out.write("<script src=\"../js/bootstrap.min.js\"></script>\n");
      out.write("<script src=\"../js/handsontable-master/dist/handsontable.full.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" media=\"screen\"\n");
      out.write("\thref=\"../js/handsontable-master/dist/handsontable.full.css\">\n");
      out.write("<script src=\"../js/adamwdraper-Numeral-js-7487acb/min/numeral.min.js\"></script>\n");
      out.write("<script src=\"../js/moment.js\"></script>\n");
      out.write("<script\n");
      out.write("\tsrc=\"../js/handsontable-master/dist/zeroclipboard/ZeroClipboard.js\">\n");
      out.write("\t\n");
      out.write("</script>\n");
      out.write("<script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\n");
      out.write("        \n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t<div class=\"container-fluid\">\n");
      out.write("\n");
      out.write("\t\t<nav class=\"navbar navbar-inverse\">\n");
      out.write("\t\t\t<div class=\"container-fluid\">\n");
      out.write("\t\t\t\t<div class=\"navbar-header\">\n");
      out.write("\t\t\t\t\t<a class=\"navbar-brand\" href=\"#\">SyntacticReferenceCorpusOfMedievalFrench-NLP</a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav\">\n");
      out.write("\t\t\t\t\t<li class=\"active\"><a href=\"#\"><span class=\"glyphicon glyphicon-home\"></span>Home</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Apply texts models</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Apply full model</a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("\t\t\t\t\t<li><a id=\"exit\" href=\"#\"><span class=\"glyphicon glyphicon-off\"></span></a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</nav>\n");
      out.write("\n");
      out.write("\t\t<div class=\"jumbotron\">\n");
      out.write("\t\t\t<h1>Apply texts models</h1>\n");
      out.write("\t\t\t<p>Here you can choose a model based on one text of the SRCMF, to apply on another one.\n");
      out.write("\t\t\tYou can also import a file to test models on another corpus.</p>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\t\t\t<div class=\"col-sm-4\">\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"col-sm-4\">\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- <form action=\"ooo\" method=\"post\"> -->\n");
      out.write("\t\t\t\t\t<input id=\"button\" class=\"btn btn-primary\" type=\"submit\" name=\"button1\" value=\"Launch API\" />\n");
      out.write("\t\t\t\t<!-- </form> -->\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"col-sm-4\"></div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("document.getElementById(\"button\").addEventListener(\"click\", displayLoad);\n");
      out.write("function displayLoad() {\n");
      out.write("\tvar opts = {\n");
      out.write("\t\t\t  lines: 11 // The number of lines to draw\n");
      out.write("\t\t\t, length: 56 // The length of each line\n");
      out.write("\t\t\t, width: 31 // The line thickness\n");
      out.write("\t\t\t, radius: 64 // The radius of the inner circle\n");
      out.write("\t\t\t, scale: 1 // Scales overall size of the spinner\n");
      out.write("\t\t\t, corners: 1 // Corner roundness (0..1)\n");
      out.write("\t\t\t, color: '#000' // #rgb or #rrggbb or array of colors\n");
      out.write("\t\t\t, opacity: 0.2 // Opacity of the lines\n");
      out.write("\t\t\t, rotate: 0 // The rotation offset\n");
      out.write("\t\t\t, direction: 1 // 1: clockwise, -1: counterclockwise\n");
      out.write("\t\t\t, speed: 1.1 // Rounds per second\n");
      out.write("\t\t\t, trail: 58 // Afterglow percentage\n");
      out.write("\t\t\t, fps: 20 // Frames per second when using setTimeout() as a fallback for CSS\n");
      out.write("\t\t\t, zIndex: 2e9 // The z-index (defaults to 2000000000)\n");
      out.write("\t\t\t, className: 'spinner' // The CSS class to assign to the spinner\n");
      out.write("\t\t\t, top: '49%' // Top position relative to parent\n");
      out.write("\t\t\t, left: '50%' // Left position relative to parent\n");
      out.write("\t\t\t, shadow: true // Whether to render a shadow\n");
      out.write("\t\t\t, hwaccel: false // Whether to use hardware acceleration\n");
      out.write("\t\t\t, position: 'absolute' // Element positioning\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tvar target = document.getElementById('jumbotron')\n");
      out.write("\t\t\tvar spinner = new Spinner(opts).spin(target);\n");
      out.write("}\n");
      out.write("/* $(document).on(\"click\", \"#button\", function() { // When HTML DOM \"click\" event is invoked on element with ID \"somebutton\", execute the following function...\n");
      out.write("   $.get(\"/loading\", function(responseText) {   // Execute Ajax GET request on URL of \"someservlet\" and execute the following function with Ajax response text...\n");
      out.write("   \twindow.location.replace(\"/jsp/loading.jsp\");          // Locate HTML DOM element with ID \"somediv\" and set its text content with the response text.\n");
      out.write("   });\n");
      out.write("}); */\n");
      out.write("$(document).on(\"click\", \"#button\", function() { // When HTML DOM \"click\" event is invoked on element with ID \"somebutton\", execute the following function...\n");
      out.write("    window.location.replace(\"/jsp/loading.jsp\");\n");
      out.write("\t $.get(\"/loading?action=1on1\");\n");
      out.write("});\n");
      out.write("$(document).on(\"click\", \"#exit\", function() { \n");
      out.write("    window.location.replace(\"/jsp/exit.jsp\");\n");
      out.write("\t $.get(\"/exit\");\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
